import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :pulse_ox_platform, PulseOxPlatformWeb.Endpoint,
  url: [host: "localhost", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :pulse_ox_platform, PulseOxPlatform.Repo,
  database: "pulse_ox",
  username: "pulseox",
  password: "pulseoximeter",
  hostname: "localhost"

config :logger, level: :info

import_config "prod.secret.exs"
